// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEmneNVbga8kibTT97X1wphkDNmM70xg',
    appId: '1:12606492245:web:5c3758383b60ceefbb8edc',
    messagingSenderId: '12606492245',
    projectId: 'event-app-2024-exam',
    authDomain: 'event-app-2024-exam.firebaseapp.com',
    storageBucket: 'event-app-2024-exam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjugRaNMAQ-ogxz27wv68FnhnJcnOkKiQ',
    appId: '1:12606492245:android:a98c92743087aa61bb8edc',
    messagingSenderId: '12606492245',
    projectId: 'event-app-2024-exam',
    storageBucket: 'event-app-2024-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bugaaiHDTf45_duOzKyRwF_j3TgIO7c',
    appId: '1:12606492245:ios:1ff35cbcd754af67bb8edc',
    messagingSenderId: '12606492245',
    projectId: 'event-app-2024-exam',
    storageBucket: 'event-app-2024-exam.appspot.com',
    iosBundleId: 'com.example.examEventApp',
  );
}
